### ISSUE TITLE
Not Loading on VSTS Scrum Projet

### ISSUE THREAD

**Issue by drobertson123** [jgarverick/RequirementsIntegrator#3]
I would love to give you more details, but this is all I have. I added Requirements Integrator via the market place. When I go to use it in my VSTS Scrum project I get the following line;

"Requirements Integrator by Josh Garverick failed to load.Learn More about this extension, including available support options."

That is the sum total of the error information I have, sorry.

**Comment by jgarverick** [comment]
I'm sorry to hear that! I'll have a look and get that straightened out ASAP.

**Comment by drobertson123** [comment]
Np, looking forward to see it working. I wish I could give you better diagnostics info.

**Comment by jgarverick** [comment]
No worries.  The issue was with the manifest and packaging.  I have updated the extension (v1.3.2) and I have manually verified that everything works.  If you have any other feedback, please feel free to let me know!

**Comment by jgarverick** [comment]
If this flares up again, please reopen this case or submit a new one. Thank you!
