### ISSUE TITLE
Unable to upload requirements

### ISSUE THREAD

**Issue by QBCC-Mal** [jgarverick/RequirementsIntegrator#4]
Hi Josh,

This add-in looks great, and is exactly what one of our project teams was looking for! Unfortunately, we're unable to upload any requirements. We're using the latest template, then when we select Import and choose a file it just adds a second blue bar with the "It appears you do not have any requirements" message.

Multiple users have tried, and we've tried saving in Excel 97-2003 (xls), Excel (xlsx) and CSV formats, with the default or other file names. Can you offer some suggestions?

Thanks,

Mal.

**Comment by jgarverick** [comment]
Hi Mal,
Sorry for the delay! Could you please let me know what browser(s) you've tried, along with   any particulars about the file (number of rows, any special characters, etc)? Please let me know and I'll be happy to investigate. Thanks!

Josh

-----Original Message-----

**Comment by QBCC-Mal** [comment]
Hi Josh,

Thanks for getting back to me so quickly! The files used the sample template format, and even that template without any changes gets the same result. The problem occurs when I am using IE11.

After getting your email I tried with Chrome. Interestingly, the Requirements list had a whole bunch of empty requirements, presumably from the failed import attempts. I selected all these and deleted then re-imported and the requirements came in fine. Will continue with Chrome and see how we go with the rest of the mapping function.

Let me know if you need more information. Unfortunately I can’t send you the file we’re using due to confidentiality restrictions.

Cheers,

Mal.

**Comment by jgarverick** [comment]
Well I'm glad it's not a fail across the board. 😊  I will look into the IE issue on my side. If you have any other feedback just give me a shout!

-----Original Message-----
