### ISSUE TITLE
Updates forecast?

### ISSUE THREAD

**Issue by hugomssantos** [jgarverick/RequirementsIntegrator#5]
Hello,
nice extension with great potential.
But it seems like there's no updates.
is there any forecast on updates? 
Really like the extension but needs to be updated to become more useful.

Some nice features to add:
- Enable multiple import operations
- Export image from requirement visualization
- Add Requirement list to work item details

Thank you

Hugo Santos

**Comment by jgarverick** [comment]
Thanks for the great feedback, Hugo! Truth be told, I've been a bit busy lately and haven't had a chance to do much with this.  Would you mind expanding on your first feature request a bit?

I'm always up for pull requests too... 😄
